services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  custom_app:
    build: ./  #this means Dockerfile
    ports:
      - "3000:3000"

volumes:
  mongodb-data:
