{{/* This whole resource will only be created if ingress.enabled is true in values.yaml */}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-mongo-app.fullname" . }}-ingress
  labels:
    {{- include "my-mongo-app.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "my-mongo-app.fullname" . }}-mongo-express-service
                port:
                  number: {{ .Values.mongoExpress.service.port }}
{{- end }}