apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-mongo-app.fullname" . }}-mongodb
  labels:
    {{- include "my-mongo-app.labels" . | nindent 4 }}
spec:
  # The number of replicas is taken from values.yaml
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      # This selector is used by the Deployment to find the Pods it should manage.
      app.kubernetes.io/name: {{ include "my-mongo-app.fullname" . }}-mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        # These labels are applied to the Pods, so the selector above can find them.
        app.kubernetes.io/name: {{ include "my-mongo-app.fullname" . }}-mongodb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mongodb
          # The image name and tag are built dynamically from values.yaml
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  # The name of the Secret is also generated by the helper template for consistency.
                  name: {{ include "my-mongo-app.fullname" . }}-mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-mongo-app.fullname" . }}-mongodb-secret
                  key: mongo-root-password
          {{- if .Values.mongodb.persistence.enabled }}
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          {{- end }}
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "my-mongo-app.fullname" . }}-mongodb-pvc
      {{- end }}