apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-mongo-app.fullname" . }}-mongodb-secret
  labels:
    # The '| nindent 4' part ensures the entire block of labels is indented correctly by 4 spaces.
    {{- include "my-mongo-app.labels" . | nindent 4 }}
type: Opaque
# 'stringData' is used instead of 'data' because it allows us to provide plain-text
# values here, and Helm/Kubernetes will handle the base64 encoding automatically.
stringData:
  # The '| quote' function wraps the final value in quotes to ensure it's a valid string.
  mongo-root-username: {{ .Values.mongodb.auth.rootUser | quote }}
  mongo-root-password: {{ .Values.mongodb.auth.rootPassword | quote }}